//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeolocationTCP.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeolocationTCP.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Network settings.
        /// </summary>
        internal static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Last location update.
        /// </summary>
        internal static string groupBox2_Text {
            get {
                return ResourceManager.GetString("groupBox2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Speed.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GNSS source:.
        /// </summary>
        internal static string label10_Text {
            get {
                return ResourceManager.GetString("label10_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lat.
        /// </summary>
        internal static string label11_Text {
            get {
                return ResourceManager.GetString("label11_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lon.
        /// </summary>
        internal static string label15_Text {
            get {
                return ResourceManager.GetString("label15_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Protocol.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Address.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DataPort.
        /// </summary>
        internal static string label6_Text {
            get {
                return ResourceManager.GetString("label6_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Accuracy.
        /// </summary>
        internal static string label8_Text {
            get {
                return ResourceManager.GetString("label8_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GNSS status:.
        /// </summary>
        internal static string label9_Text {
            get {
                return ResourceManager.GetString("label9_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cellular.
        /// </summary>
        internal static string Source_Cellular {
            get {
                return ResourceManager.GetString("Source_Cellular", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Default.
        /// </summary>
        internal static string Source_Default {
            get {
                return ResourceManager.GetString("Source_Default", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu IP Address.
        /// </summary>
        internal static string Source_IPAddress {
            get {
                return ResourceManager.GetString("Source_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obfuscated.
        /// </summary>
        internal static string Source_Obfuscated {
            get {
                return ResourceManager.GetString("Source_Obfuscated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Satellite (GNSS).
        /// </summary>
        internal static string Source_Satellite {
            get {
                return ResourceManager.GetString("Source_Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unknown.
        /// </summary>
        internal static string Source_Unknown {
            get {
                return ResourceManager.GetString("Source_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wi-Fi.
        /// </summary>
        internal static string Source_WiFi {
            get {
                return ResourceManager.GetString("Source_WiFi", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Disabled.
        /// </summary>
        internal static string Status_Disabled {
            get {
                return ResourceManager.GetString("Status_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Initializing....
        /// </summary>
        internal static string Status_Initializing {
            get {
                return ResourceManager.GetString("Status_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No data.
        /// </summary>
        internal static string Status_NoData {
            get {
                return ResourceManager.GetString("Status_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Not initialized.
        /// </summary>
        internal static string Status_NotInitialized {
            get {
                return ResourceManager.GetString("Status_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ready.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unknown.
        /// </summary>
        internal static string Status_Unknown {
            get {
                return ResourceManager.GetString("Status_Unknown", resourceCulture);
            }
        }
    }
}
